In [1]:
import sys  
sys.path.append('../../../')
sys.path.append('../../../Model')

In [9]:
from Model.researcher.update.researcher_updater import ResearcherUpdater
from db.loadjson import get_data

In [22]:
test_df = get_data()
test_df.rename(columns={'field_id': 'division', 'name': 'tag'}, inplace=True)

In [23]:
test_df

,email,university,divisions,tags
0,123@anu.edu.au,University of Canberra,[d_05],
1,1@1.com,Charles Sturt University,[d_04],
2,1@a.com,Australian National University,"[d_08, d_10]",[machine learning]
3,a@a.com,Australian National University,"[d_04, d_05, d_06]",[Health]
4,a@anu.com,Australian National University,"[d_04, d_05, d_17]",
5,a@b.com,University of Canberra,"[d_03, d_06, d_07]",
6,aa@a.com,University of Canberra,"[d_04, d_05]",
7,anu@anu.com,Australian National University,"[d_01, d_03, d_04]",
8,b@anu.com,Charles Sturt University,"[d_02, d_03, d_18]",
9,blank@blank.com,Australian National University,[d_04],
10,carl.carla@hotmail.com,Australian National University,"[d_01, d_08, d_17]",
11,Ryanyang@anu.com,University of Canberra,"[d_20, d_21, d_22]",[Human]
12,test2@anu.com,Australian National University,"[d_04, d_20, d_22]",
13,test3@anu.com,Australian National University,"[d_15, d_20, d_22]",
14,test@test.com,Australian National University,[d_04],
15,u7190388@anu.edu.au,Australian National University,[d_08],[DATA SCIENCES]
16,u7194259@anu.edu.au,Australian National University,[d_08],
17,u7195896@anu.edu.au,Australian National University,[d_08],
18,v@v.com,University of Canberra,"[d_06, d_08, d_12]",

In [24]:
test_df[['email', 'tag']].explode('tag')

KeyError: "['tag'] not in index"

In [10]:
input_df = rup.reg_info

In [11]:
input_df['id'] = 'Reg_'+ input_df['email']

In [13]:
input_df['field_id'].tolist()

['ENVIRONMENTAL',
 'EARTH',
 'INFORMATION AND COMPUTING',
 'TECHNOLOGY',
 'EARTH',
 'ENVIRONMENTAL',
 'BIOLOGICAL',
 'EARTH',
 'ENVIRONMENTAL',
 'PSYCHOLOGY AND COGNITIVE SCIENCES',
 'CHEMICAL',
 'BIOLOGICAL',
 'AGRICULTURAL AND VETERINARY',
 'EARTH',
 'ENVIRONMENTAL',
 'MATHEMATICAL',
 'CHEMICAL',
 'EARTH',
 'PHYSICAL',
 'CHEMICAL',
 'LAW AND LEGAL STUDIES',
 'EARTH',
 'MATHEMATICAL',
 'INFORMATION AND COMPUTING',
 'PSYCHOLOGY AND COGNITIVE SCIENCES',
 'LANGUAGE, COMMUNICATION AND CULTURE',
 'HISTORY AND ARCHAEOLOGY',
 'PHILOSOPHY AND RELIGIOUS STUDIES',
 'EARTH',
 'LANGUAGE, COMMUNICATION AND CULTURE',
 'PHILOSOPHY AND RELIGIOUS STUDIES',
 'COMMERCE, MANAGEMENT, TOURISM AND SERVICES',
 'LANGUAGE, COMMUNICATION AND CULTURE',
 'PHILOSOPHY AND RELIGIOUS STUDIES',
 'EARTH',
 'INFORMATION AND COMPUTING',
 'INFORMATION AND COMPUTING',
 'INFORMATION AND COMPUTING',
 'BIOLOGICAL',
 'INFORMATION AND COMPUTING',
 'BUILT ENVIRONMENT AND DESIGN']