In [1]:
import pandas as pd, numpy as np

In [2]:
relation_df = pd.read_csv('data/tag_category_map.csv')
staff_df = pd.read_csv('data/clean_staff_tags.csv')

In [3]:
staff_df = staff_df.drop(['_id','tagsType'], axis=1)
staff_df['Tags'] = staff_df['Tags'].str.lower()

In [4]:
staff_agg_df = staff_df.groupby(['Name','Staff ID'])['Tags'].apply(lambda x: list(set(x))).reset_index()

In [10]:
sample_reseacher_tag_df = staff_agg_df.sample(1)

In [11]:
sample_reseacher_tag_df

,Name,Staff ID,Tags
360,Vivienne Lewis,Canberra00219,"[skin, type frequency, e-health, objectificati..."

In [12]:
sample_reseacher_tag_df = sample_reseacher_tag_df.explode('Tags')

sample_tags_df = sample_reseacher_tag_df.merge(relation_df)

In [13]:
sample_tags_df

,Name,Staff ID,Tags,value
0,Vivienne Lewis,Canberra00219,skin,DIVISION 23 OTHERS(RELEVANT)
1,Vivienne Lewis,Canberra00219,weights and measures,DIVISION 23 OTHERS(RELEVANT)
2,Vivienne Lewis,Canberra00219,shame,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
3,Vivienne Lewis,Canberra00219,self concept,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
4,Vivienne Lewis,Canberra00219,age groups,DIVISION 23 OTHERS(RELEVANT)
5,Vivienne Lewis,Canberra00219,parents,DIVISION 24 OTHERS(IRRELEVANT)
6,Vivienne Lewis,Canberra00219,confidence,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
7,Vivienne Lewis,Canberra00219,therapeutics,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
8,Vivienne Lewis,Canberra00219,body weight,DIVISION 11 MEDICAL AND HEALTH SCIENCES
9,Vivienne Lewis,Canberra00219,child,DIVISION 06 BIOLOGICAL SCIENCES
10,Vivienne Lewis,Canberra00219,middle aged,DIVISION 11 MEDICAL AND HEALTH SCIENCES
11,Vivienne Lewis,Canberra00219,obesity,DIVISION 11 MEDICAL AND HEALTH SCIENCES
12,Vivienne Lewis,Canberra00219,mental health,DIVISION 11 MEDICAL AND HEALTH SCIENCES
13,Vivienne Lewis,Canberra00219,mental health,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
14,Vivienne Lewis,Canberra00219,health,DIVISION 11 MEDICAL AND HEALTH SCIENCES
15,Vivienne Lewis,Canberra00219,ehealth,DIVISION 11 MEDICAL AND HEALTH SCIENCES
16,Vivienne Lewis,Canberra00219,narcissism,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
17,Vivienne Lewis,Canberra00219,psychology student,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
18,Vivienne Lewis,Canberra00219,exercise,DIVISION 13 EDUCATION
19,Vivienne Lewis,Canberra00219,program evaluation,DIVISION 09 ENGINEERING
20,Vivienne Lewis,Canberra00219,program evaluation,"DIVISION 15 COMMERCE, MANAGEMENT, TOURISM AND ..."
21,Vivienne Lewis,Canberra00219,wounds and injuries,DIVISION 11 MEDICAL AND HEALTH SCIENCES
22,Vivienne Lewis,Canberra00219,wounds and injuries,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
23,Vivienne Lewis,Canberra00219,trauma,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
24,Vivienne Lewis,Canberra00219,social inequality,DIVISION 16 STUDIES IN HUMAN SOCIETY
25,Vivienne Lewis,Canberra00219,worldview,DIVISION 16 STUDIES IN HUMAN SOCIETY
26,Vivienne Lewis,Canberra00219,ego,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
27,Vivienne Lewis,Canberra00219,students,DIVISION 13 EDUCATION
28,Vivienne Lewis,Canberra00219,feeding and eating disorders,DIVISION 11 MEDICAL AND HEALTH SCIENCES
29,Vivienne Lewis,Canberra00219,feeding and eating disorders,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
30,Vivienne Lewis,Canberra00219,muscles,DIVISION 11 MEDICAL AND HEALTH SCIENCES
31,Vivienne Lewis,Canberra00219,muscles,DIVISION 06 BIOLOGICAL SCIENCES
32,Vivienne Lewis,Canberra00219,ecological momentary assessment,DIVISION 05 ENVIRONMENTAL SCIENCES
33,Vivienne Lewis,Canberra00219,eating behavior,DIVISION 11 MEDICAL AND HEALTH SCIENCES
34,Vivienne Lewis,Canberra00219,self report,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
35,Vivienne Lewis,Canberra00219,self report,DIVISION 23 OTHERS(RELEVANT)
36,Vivienne Lewis,Canberra00219,curriculum,DIVISION 13 EDUCATION
37,Vivienne Lewis,Canberra00219,social theory,DIVISION 16 STUDIES IN HUMAN SOCIETY
38,Vivienne Lewis,Canberra00219,body image,DIVISION 11 MEDICAL AND HEALTH SCIENCES
39,Vivienne Lewis,Canberra00219,feeding behavior,DIVISION 06 BIOLOGICAL SCIENCES
40,Vivienne Lewis,Canberra00219,cognitive behavioral therapy,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
41,Vivienne Lewis,Canberra00219,interpersonal relations,"DIVISION 20 LANGUAGE, COMMUNICATION AND CULTURE"
42,Vivienne Lewis,Canberra00219,telemedicine,DIVISION 11 MEDICAL AND HEALTH SCIENCES
43,Vivienne Lewis,Canberra00219,telemedicine,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
44,Vivienne Lewis,Canberra00219,psychology,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
45,Vivienne Lewis,Canberra00219,caregivers,DIVISION 11 MEDICAL AND HEALTH SCIENCES
46,Vivienne Lewis,Canberra00219,conflict (psychology),DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
47,Vivienne Lewis,Canberra00219,eating,DIVISION 24 OTHERS(IRRELEVANT)
48,Vivienne Lewis,Canberra00219,gender role,DIVISION 16 STUDIES IN HUMAN SOCIETY
49,Vivienne Lewis,Canberra00219,gender role,DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES
50,Vivienne Lewis,Canberra00219,audit,DIVISION 14 ECONOMICS
51,Vivienne Lewis,Canberra00219,audit,"DIVISION 15 COMMERCE, MANAGEMENT, TOURISM AND ..."
52,Vivienne Lewis,Canberra00219,nutritionists,DIVISION 11 MEDICAL AND HEALTH SCIENCES

In [14]:
sample_tags_df = sample_tags_df[sample_tags_df['value']!='DIVISION 24 OTHERS(IRRELEVANT)'][['Staff ID', 'Tags']]

remain_df = staff_df[staff_df['Staff ID'] != sample_tags_df['Staff ID'].unique()[0]]
candidate_df = remain_df[remain_df['Tags'].isin(sample_tags_df['Tags'])]
candidate_df = candidate_df.groupby('Staff ID')['Weight'].sum().reset_index().sort_values('Weight', ascending=False)
sim_df = candidate_df[:10]
sim_df

          Staff ID  Weight
154  Canberra00280   17.58
38   Canberra00070   17.29
20   Canberra00037   12.33
126  Canberra00237   11.32
148  Canberra00272   10.52
191  Canberra00335    9.74
150  Canberra00276    9.53
24   Canberra00041    9.45
165  Canberra00295    9.29
103  Canberra00188    9.14

In [22]:
staff_df[staff_df['Staff ID'] == 'Canberra00292']

,Name,Staff ID,Tags,Weight
16584,Holly Louise Northam,Canberra00292,tissue and organ procurement,1.00
16585,Holly Louise Northam,Canberra00292,nurse practitioners,0.49
16586,Holly Louise Northam,Canberra00292,bereavement,0.36
16587,Holly Louise Northam,Canberra00292,primary health care,0.30
16588,Holly Louise Northam,Canberra00292,tissue donors,0.30
...,...,...,...,...
45995,Holly Louise Northam,Canberra00292,death,0.09
45996,Holly Louise Northam,Canberra00292,chronic diseases,0.07
45997,Holly Louise Northam,Canberra00292,population,0.08
45998,Holly Louise Northam,Canberra00292,organ transplantation,0.07
45999,Holly Louise Northam,Canberra00292,tissue transplantation,0.53

In [20]:
staff_df[staff_df['Staff ID'] == 'Canberra00383']

                   Name       Staff ID                       Tags  Weight
21893  Karen Strickland  Canberra00383                     nurses    1.00
21894  Karen Strickland  Canberra00383                    nursing    0.98
21895  Karen Strickland  Canberra00383         multiple sclerosis    0.92
21896  Karen Strickland  Canberra00383                   webcasts    0.56
21897  Karen Strickland  Canberra00383                elder abuse    0.54
...                 ...            ...                        ...     ...
52775  Karen Strickland  Canberra00383           breast neoplasms    1.00
52776  Karen Strickland  Canberra00383                    anxiety    0.23
52777  Karen Strickland  Canberra00383  referral and consultation    0.57
52778  Karen Strickland  Canberra00383                 congresses    0.38
52779  Karen Strickland  Canberra00383               publications    0.32

[140 rows x 4 columns]

In [6]:
agg_weight_df = staff_df.merge(relation_df).groupby(['Name', 'value'])['Weight'].sum().reset_index()

In [7]:
agg_weight_df = agg_weight_df.sort_values('Weight', ascending=False)

In [59]:
agg_weight_df[agg_weight_df['Name'] == 'Mehves Cetinkaya Sendas']

,Name,value,Weight
3671,Mehves Cetinkaya Sendas,DIVISION 19 STUDIES IN CREATIVE ARTS AND WRITING,1.75
3673,Mehves Cetinkaya Sendas,DIVISION 23 OTHERS(RELEVANT),1.62
3666,Mehves Cetinkaya Sendas,DIVISION 09 ENGINEERING,1.21
3665,Mehves Cetinkaya Sendas,DIVISION 08 INFORMATION AND COMPUTING SCIENCES,0.88
3674,Mehves Cetinkaya Sendas,DIVISION 24 OTHERS(IRRELEVANT),0.42
3668,Mehves Cetinkaya Sendas,DIVISION 13 EDUCATION,0.34
3672,Mehves Cetinkaya Sendas,DIVISION 21 HISTORY AND ARCHAEOLOGY,0.34
3670,Mehves Cetinkaya Sendas,DIVISION 16 STUDIES IN HUMAN SOCIETY,0.22
3669,Mehves Cetinkaya Sendas,DIVISION 14 ECONOMICS,0.15
3667,Mehves Cetinkaya Sendas,DIVISION 12 BUILT ENVIRONMENT AND DESIGN,0.10

In [8]:
result_df = agg_weight_df.drop_duplicates('Name')

In [9]:
result_df

,Name,value,Weight
5244,Stephen Sarre,DIVISION 06 BIOLOGICAL SCIENCES,47.56
2240,Jane Kellett,DIVISION 11 MEDICAL AND HEALTH SCIENCES,45.72
5422,Theo Niyonsenga,DIVISION 11 MEDICAL AND HEALTH SCIENCES,40.97
3513,Mark Naunton,DIVISION 11 MEDICAL AND HEALTH SCIENCES,40.87
220,Andrew Mckune,DIVISION 11 MEDICAL AND HEALTH SCIENCES,40.12
...,...,...,...
473,Ben Ennis Butler,DIVISION 08 INFORMATION AND COMPUTING SCIENCES,1.80
1417,Dr. Andrew Woodward,DIVISION 11 MEDICAL AND HEALTH SCIENCES,1.76
3671,Mehves Cetinkaya Sendas,DIVISION 19 STUDIES IN CREATIVE ARTS AND WRITING,1.75
2376,Jemima Yarnold,DIVISION 24 OTHERS(IRRELEVANT),1.55
230,Angela Tan-Kantor,DIVISION 04 EARTH SCIENCES,1.18

In [64]:
result_df[result_df['value'] == 'DIVISION 24 OTHERS(IRRELEVANT)']

,Name,value,Weight
3967,Moo Sung Lee,DIVISION 24 OTHERS(IRRELEVANT),22.38
3899,Milind Sathye,DIVISION 24 OTHERS(IRRELEVANT),22.22
3380,Majharul Talukder,DIVISION 24 OTHERS(IRRELEVANT),19.21
4354,Petra Buergelt,DIVISION 24 OTHERS(IRRELEVANT),19.00
4983,Sarah Maslen,DIVISION 24 OTHERS(IRRELEVANT),18.86
5597,Tracey Dickson,DIVISION 24 OTHERS(IRRELEVANT),17.71
1400,"Dr Henry Liu, PhD, MPhil, MSc, LLB (Hons), FHEA",DIVISION 24 OTHERS(IRRELEVANT),17.41
844,Cathy Hope,DIVISION 24 OTHERS(IRRELEVANT),15.10
1069,Darren Sinclair,DIVISION 24 OTHERS(IRRELEVANT),14.81
499,Ben Freyens,DIVISION 24 OTHERS(IRRELEVANT),13.99
614,Bethaney Turner,DIVISION 24 OTHERS(IRRELEVANT),13.79
3591,Mathieu O'Neil,DIVISION 24 OTHERS(IRRELEVANT),13.30
1500,Eleni Petraki,DIVISION 24 OTHERS(IRRELEVANT),12.41
5745,Vincent Learnihan,DIVISION 24 OTHERS(IRRELEVANT),12.07
794,Catherine Ordway,DIVISION 24 OTHERS(IRRELEVANT),11.81
58,Ahmed Imran,DIVISION 24 OTHERS(IRRELEVANT),11.77
4268,Peter Bodycott,DIVISION 24 OTHERS(IRRELEVANT),11.12
1620,"Fanke Peng, SFHEA",DIVISION 24 OTHERS(IRRELEVANT),11.07
393,Barbara Norman,DIVISION 24 OTHERS(IRRELEVANT),10.42
2218,James Robertson,DIVISION 24 OTHERS(IRRELEVANT),10.26
1194,Deborah Pino Pasternak,DIVISION 24 OTHERS(IRRELEVANT),10.17
5613,Tracy Ireland,DIVISION 24 OTHERS(IRRELEVANT),9.92
304,Annie Mccarthy,DIVISION 24 OTHERS(IRRELEVANT),9.42
3111,Kym Simoncini,DIVISION 24 OTHERS(IRRELEVANT),9.30
1228,Denise Thwaites,DIVISION 24 OTHERS(IRRELEVANT),9.08
3916,Mirani Litster,DIVISION 24 OTHERS(IRRELEVANT),8.96
2328,Jason Bainbridge,DIVISION 24 OTHERS(IRRELEVANT),8.83
1482,Eddi Pianca,DIVISION 24 OTHERS(IRRELEVANT),8.71
4495,Raghu Gudur,DIVISION 24 OTHERS(IRRELEVANT),8.40
2075,Irfan Khan,DIVISION 24 OTHERS(IRRELEVANT),8.34
3708,Mel Mylek,DIVISION 24 OTHERS(IRRELEVANT),8.25
2987,Kelly Mazzer,DIVISION 24 OTHERS(IRRELEVANT),7.93
4301,Peter Putnis,DIVISION 24 OTHERS(IRRELEVANT),7.29
2123,Ivana Damjanovic,DIVISION 24 OTHERS(IRRELEVANT),6.69
5472,Tim Sherratt,DIVISION 24 OTHERS(IRRELEVANT),6.34
2501,Jenny Fu,DIVISION 24 OTHERS(IRRELEVANT),6.25
5007,Sarvjeet Kaur Chatrath,DIVISION 24 OTHERS(IRRELEVANT),6.07
1177,Deborah Hill,DIVISION 24 OTHERS(IRRELEVANT),5.86
1435,"Dr. John Ting, PhD",DIVISION 24 OTHERS(IRRELEVANT),5.07
3391,Maree Sainsbury,DIVISION 24 OTHERS(IRRELEVANT),4.78
1129,David Paterson,DIVISION 24 OTHERS(IRRELEVANT),4.21
1794,Gevork Hartoonian,DIVISION 24 OTHERS(IRRELEVANT),4.19
2487,Jenny Dean,DIVISION 24 OTHERS(IRRELEVANT),4.01
1001,Dale Kleeman,DIVISION 24 OTHERS(IRRELEVANT),3.23
1601,Ernest Koh,DIVISION 24 OTHERS(IRRELEVANT),3.23
2267,Janet Hope,DIVISION 24 OTHERS(IRRELEVANT),2.59
2308,Jaquelin Bousie,DIVISION 24 OTHERS(IRRELEVANT),2.55
5291,Stuart Cunningham,DIVISION 24 OTHERS(IRRELEVANT),2.34
2376,Jemima Yarnold,DIVISION 24 OTHERS(IRRELEVANT),1.55

In [24]:
range_dict = {}
for tag in sample_reseacher['Tags'].values[0]:
    tmp_df = relation_df[relation_df['Tags'] == tag]
    range_dict

In [26]:
set(range_list)

{'DIVISION 01 MATHEMATICAL SCIENCES',
 'DIVISION 02 PHYSICAL SCIENCES',
 'DIVISION 04 EARTH SCIENCES',
 'DIVISION 05 ENVIRONMENTAL SCIENCES',
 'DIVISION 06 BIOLOGICAL SCIENCES',
 'DIVISION 08 INFORMATION AND COMPUTING SCIENCES',
 'DIVISION 09 ENGINEERING',
 'DIVISION 10 TECHNOLOGY',
 'DIVISION 11 MEDICAL AND HEALTH SCIENCES',
 'DIVISION 13 EDUCATION',
 'DIVISION 16 STUDIES IN HUMAN SOCIETY',
 'DIVISION 17 PSYCHOLOGY AND COGNITIVE SCIENCES',
 'DIVISION 22 PHILOSOPHY AND RELIGIOUS STUDIES',
 'DIVISION 23 OTHERS(RELEVANT)',
 'DIVISION 24 OTHERS(IRRELEVANT)'}